### ISSUE TITLE
upcoming changes in HA's device_tracker

### ISSUE THREAD

**Issue by phixion** [pnbruckner/ha-composite-tracker#14]
see https://github.com/home-assistant/core/pull/32705

not sure if it affects your code but you should remove the recommendation in your README.md

**Comment by ccorderod** [comment]
Hi. The component is broken on 0.107.0b3.
`Platform error device_tracker.composite - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' (/usr/src/homeassistant/homeassistant/components/device_tracker/const.py)
Platform error device_tracker.composite - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' (/usr/src/homeassistant/homeassistant/components/device_tracker/const.py)`

**Comment by pnbruckner** [comment]
@phixion @ccorderod thanks! Let me know if this works for you.

**Comment by ccorderod** [comment]
@pnbruckner Yes it does. Thank you!.

**Comment by pnbruckner** [comment]
Note that I forgot to update the `__version__` string in `__init__.py` (see what happens when I try to rush a change? lol), so I'll probably make another release to sync that string with the actual release number.

**Comment by steveelsbury** [comment]
I still see this error in HA 108.6 - what action do we need to take to remediate?

**Comment by pnbruckner** [comment]
@steveelsbury did you upgrade this custom integration to 2.1.1? Since I messed up by not updating the internal version number it might not be easy to tell. I'll try to release 2.1.2 to fix that.

**Comment by steveelsbury** [comment]
Sorry - but how? I don't even use any kind of device trackers. This error just started appearing after the 107 upgrade. I am currently on 108.6.

**Comment by pnbruckner** [comment]
@steveelsbury please post the entire error message.

**Comment by steveelsbury** [comment]
Aha - same error, but a different component: Platform error device_tracker.huesensor - cannot import name 'ENTITY_ID_FORMAT' from 'homeassistant.components.device_tracker.const' (/usr/src/homeassistant/homeassistant/components/device_tracker/const.py)

**Comment by pnbruckner** [comment]
Yeah, although it may be suffering from the same problem, that's not this custom integration. You need to request help from author if it's also a custom integration, or open an issue against HA if it's a standard integration.

**Comment by steveelsbury** [comment]
Many thanks - my apologies for having wasted your time.
