### ISSUE TITLE
No module named 'custom_components.composite.const'

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-composite-tracker#16]
using the latest version of the Custom integration this is logged on config check:

<img width="832" alt="Schermafbeelding 2020-03-16 om 11 36 39" src="https://user-images.githubusercontent.com/33354141/76748407-fc03cd00-677a-11ea-96ef-063f39a6029e.png">
I have 6 trackers as you can see... 
have only updated the custom integration file itself, and didn't change anything to the configuration files. HA 106.6

and an error in the log for each, see my post on the community: https://community.home-assistant.io/t/composite-device-tracker-platform/67345/322

__update__

this is worse, going back to the previous release still shows the error on config check:

<img width="587" alt="Schermafbeelding 2020-03-16 om 12 07 46" src="https://user-images.githubusercontent.com/33354141/76750595-dc6ea380-677e-11ea-9c4e-46d4065f5ad8.png">

Could this be cause by updating ha 106.5 to 106.6??

please have a look?
thanks

**Comment by pnbruckner** [comment]
I just tried it with 0.106.5 and 0.106.6 and it seems to work fine with both for me. Are you sure you installed it correctly? There should be four files in `<config>/custom_components/composite`:
```
(venv) phil@GGHWFS1:~/test/ha-composite_config/custom_components/composite (master)$ ls -l
total 32
-rw-rw-r-- 1 phil phil   331 Jan 27 09:38 const.py
-rw-r--r-- 1 phil phil 13535 Mar 16 08:22 device_tracker.py
-rw-rw-r-- 1 phil phil  1679 Jan 27 10:31 __init__.py
-rw-rw-r-- 1 phil phil   231 Jan 27 09:38 manifest.json
drwxrwxr-x 2 phil phil  4096 Mar 16 08:36 __pycache__
```
I did just realize that I forgot to update the `__version__` string inside `__init__.py`, but that shouldn't matter. I'll probably issue a new release to fix that, just to be complete. But I'll wait to hear back from you first.

**Comment by Mariusthvdb** [comment]
well, now you mention.... I seem to be missing the const.py, as I only checked the latest changed files in your repo, which was the device_tracker.

I now see the const.py, which I didn't have in the first place, and didn't get issues on before. I am really stumped how this can be.

Will instal that, and report back, thanks for your quick reply

**Comment by Mariusthvdb** [comment]
sorry, too quick to close,

After having installed the latest of both const.py and the device_tracker.py, setup check as valid, but restarting gives me this:
```
2020-03-16 16:43:14 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
    discovery_info,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/composite/device_tracker.py", line 63, in setup_scanner
    CompositeScanner(hass, config, see)
  File "/config/custom_components/composite/device_tracker.py", line 92, in __init__
    self._tf = hass.data[DOMAIN]
KeyError: 'composite'
```
for each device tracked
is this something to worry about (errors always are..)?

**Comment by pnbruckner** [comment]
Did you update _ALL_ files, _including_ `__init__.py`?

**Comment by Mariusthvdb** [comment]
NO, real sorry, my mistake.
Closing...
