### ISSUE TITLE
no entity for composite device tracker

### ISSUE THREAD

**Issue by reaper7** [pnbruckner/ha-composite-tracker#17]
My HW / HA config:
```
arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.3
timezone | Europe/Warsaw
version | 0.108.8
virtualenv | true
```

configuration.yaml:
```
composite:

device_tracker: !include includes/devtrack.yaml
```

devtrack.yaml:
```
- platrorm: composite
  name mycomposite
  time_as: device_or_local
  require_movements: false
  entity_id:
    - device_tracker.myphone
    - device_tracker.google_maps_xxxxxxxxxxxxxxxxxxxxx
```

log:
```
2020-04-24 13:17:55 DEBUG (SyncWorker_19) [custom_components.composite] Process requirements suceeded: timezonefinderL==4.0.2
2020-04-24 13:18:09 DEBUG (SyncWorker_6) [custom_components.composite.device_tracker] Updating device_tracker.mycomposite from device_tracker.google_maps_xxxxxxxxxxxxxxxxxxxxx
2020-04-24 13:18:30 DEBUG (SyncWorker_1) [custom_components.composite.device_tracker] Updating device_tracker.mycomposite from device_tracker.myphone
```

but I can't find an device_tracker.mycomposite entity in HA :(
No device_tracker.mycomposite in developer tools/states

**Comment by pnbruckner** [comment]
Hmm, I can't see how that is possible. If you see the "Updating ..." output then it's calling the device tracker component level "see" method, and therefore the entity _should_ be created. Does it appear in known_devices.yaml? Honestly, haven't tested with 0.108.x. I'm still using 0.104.0 myself, although I have tested with newer dev versions (but not that recently.)

I'll try to test with the latest & greatest when I get a chance.

**Comment by reaper7** [comment]
I already know where was the problem.
My first devicetracker has set:
```
  new_device_defaults:
    track_new_devices: false
```
because bluetooth tracker added many bt devices from other people in the area,

so, the changing composite entity track to true solved the problem, already I seeing entities.

You can close this issue.

**Comment by pnbruckner** [comment]
Ah, a lot of people get bit by that. Glad you figured it out.
