### ISSUE TITLE
The see service is not supported for this entity ...

### ISSUE THREAD

**Issue by zibous** [pnbruckner/ha-composite-tracker#21]
**ERROR Message at startup:**

```txt
Protokolldetails ( ERROR )
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:184
Integration: Geräte-Tracker (documentation, issues)
First occurred: 13:03:02 (2 occurrences)
Last logged: 13:11:07
```
**Configuration**
```txt
- platform: composite
    name: XIAOMI-HANDY-RENI
    time_as: device_or_local
    require_movement: true
    entity_id:
      - device_tracker.xiaomi_handy_reni
```

**Device Info**
```txt
source_type: router
is_wired: false
hostname: RedmiNote4-timeoutno
mac: 'XX:XX:XX:XX:XX:XX'
name: XIAOMI-HANDY-RENI
oui: XiaomiCo
_is_guest_by_uap: false
ap_mac: 'XX:XX:XX:XX:XX:XX'
authorized: true
essid: XXXXXXXXXXX
ip: XX.X.X.XXX
is_11r: false
is_guest: false
noted: true
qos_policy_applied: true
radio: ng
radio_proto: ng
vlan: 0
friendly_name: XIAOMI-HANDY-RENI
```
**System**
```txt
Frontend-Version: 20200603.3 - latest
arch	x86_64
dev	false
docker	false
hassio	false
installation_type	Home Assistant Core
os_name	Linux
os_version	5.4.0-37-generic
python_version	3.8.2
timezone	Europe/Vaduz
version	0.111.4
virtualenv	true
Lovelace
dashboards	2
mode	yaml
resources	23
views	9
```

What am I doing wrong with the configuration, because all other devices work perfectly.
How can I fix the error ?
Thanks

**Comment by pnbruckner** [comment]
What is the entity_id in the error message? You left that out.

Are you trying to use the `device_tracker.see` service? If so, with what type of entity? I.e., what integration created the entity?

I don't think this error has anything to do with my custom composite integration, but further details will help to make that determination.

**Comment by zibous** [comment]
**Protokolldetails ( ERROR )**
```txt
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:184
Integration: Geräte-Tracker (documentation, issues)
First occurred: 18:17:15 (6 occurrences)
Last logged: 19:12:08

The see service is not supported for this entity device_tracker.xiaomi_handy_reni
```

**device_tracker.xiaomi_handy_reni**
```text
source_type: router
is_wired: false
hostname: RedmiNote4-timeoutno
mac: 04:b1:67:ac:35:3e
name: XIAOMI-HANDY-RENI
oui: XiaomiCo
_is_guest_by_uap: false
ap_mac: fc:ec:da:a6:0e:6a
authorized: true
essid: Microwelle
ip: 10.1.1.208
is_11r: false
is_guest: false
noted: true
qos_policy_applied: true
radio: ng
radio_proto: ng
vlan: 0
friendly_name: XIAOMI-HANDY-RENI
```

![Bildschirmfoto 2020-06-26 um 19 19 51](https://user-images.githubusercontent.com/30198737/85884271-a8296b00-b7e2-11ea-849d-9397b8d01682.png)


device_tracker.see shows no results, but I have no data for gps, gps_accuracy, battery for the device.

**Comment by pnbruckner** [comment]
Let's take a step back. You're trying to create a composite entity from `device_tracker.xiaomi_handy_reni`, but you've configued the composite entity so that it will have the _same_ `entity_id`!
```yaml
- platform: composite
    name: XIAOMI-HANDY-RENI  <== This will cause created entity_id to be device_tracker.xiaomi_handy_reni!!
    time_as: device_or_local
    require_movement: true
    entity_id:
      - device_tracker.xiaomi_handy_reni
```
You need to give the composite entity a _different_ name!

Also, what are you trying to do with the `device_tracker.see` service?

I'm really not understanding what you're ultimately trying to achieve. Maybe you could explain why you're trying to create a _composite_ device from a _single_ input device.

**Comment by zibous** [comment]
@pnbruckner 

Thanks Phil 👍, the problem was the name "XIAOMI-HANDY-RENI". 
I changed this and now all is working.


device_tracker.phones_reni | home | source_type: gps latitude: 47.457897 longitude: 9.63564 gps_accuracy: 0 time_zone: Europe/Zurich entity_id: device_tracker.xiaomi_handy_reni last_entity_id: device_tracker.xiaomi_handy_reni last_seen: 2020-06-26T20:28:06+02:00 friendly_name: phones_reni
-- | -- | --
