### ISSUE TITLE
add country_code to device_trackers attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-composite-tracker#23]
please consider adding the attribute `country_code` to the device_tracker. I was hoping since you've enabled the external library for calculating the timezone, this would also provide the country_code in the data to be added.

country_code is very useful data to base other presence login in, and, except for the core mobile_app device_tracker, none of the device_trackers provide it. 

Of course, not all devices have the mobile app installed, and that's where custom integrations come into play.

As a matter of fact I've been using an AD app (importing from geopy) for some time to get the additional attributes into the core device_trackers, but as of late this has somehow stopped to be reliable. Seems the core device_trackers update even without statechange and delete the additional attributes.

Adding country_code to the Composite integration would be a  fine enhancement which I hope could be do-able.

thanks for considering

**Comment by pnbruckner** [comment]
The package used is either timezonefinder or timezonefinderL. Neither of these packages have provisions for determining country code.
