### ISSUE TITLE
After updating Life360 platform - wrong "battery" attribute

### ISSUE THREAD

**Issue by ildar170975** [pnbruckner/ha-composite-tracker#29]
Recently Life360 platform was updated.
One of the changes was that `battery` attribute now is `battery_level`.
I guess this is a reason why currently the Composite platform reports a wrong battery level value.

**Update:** it happens sometimes.
And currently the composite platform in my setup depends on Life360 device_trackers only.

If there is nothing wrong with the composite platform and the recent changes in Life360 did not affect the composite platform - I will keep searching for my internal problems.

**Comment by pnbruckner** [comment]
This custom integration already looks for either `battery` or `battery_level`, since some integrations use one, and some use the other. See:

https://github.com/pnbruckner/ha-composite-tracker/blob/3e9cc0dee3e58f0fd659257e36ee66631c537b6c/custom_components/composite/device_tracker.py#L207-L209

**Comment by ildar170975** [comment]
OK, then I keep searching for my internal reasons, thank you for clarifications!
