### ISSUE TITLE
Question: bayesian support?

### ISSUE THREAD

**Issue by rdehuyss** [pnbruckner/ha-composite-tracker#4]
Small question: will you also support bayesian inference? I know it is possible with a binary sensor but in my head it makes more sense to directly integrate it in the composite device tracker.

**Comment by pnbruckner** [comment]
Sorry @rdehuyss, I just noticed this issue. Not sure why I didn't get a notification when you created it. Hmm.

I don't have any plans to do so. First, I don't use it, so I don't know much about it. Second, it already exists, as you say, in the Bayesian Binary Sensor, and I think I prefer separate "building blocks." But honestly I haven't given it any real thought.

I'll leave this open as a reminder, but I wouldn't expect anything any time soon. 😃
