### ISSUE TITLE
Error "Failed to load resource" (probably related to the platform's icon)

### ISSUE THREAD

**Issue by ildar170975** [pnbruckner/ha-composite-tracker#41]
Getting this error in Code Inspector:

![изображение](https://user-images.githubusercontent.com/71872483/215295408-cde2a042-9dc7-4f7a-ad1c-832196699dac.png)

Seems to be related to the Composite platform:

![изображение](https://user-images.githubusercontent.com/71872483/215295420-5980d0bf-2d60-4e5a-85ec-ee98cb3edc97.png)

Meanwhile, no icon is displayed on the "Integrations" page:

![изображение](https://user-images.githubusercontent.com/71872483/215295442-866f8b3e-305e-42e2-9e8b-fedc8802e575.png)

**Comment by pnbruckner** [comment]
I'm not familiar with Code Inspector. But, yes, there is no icon defined for this custom integration in brands.home-assistant.io, although I'm aware of that and have been considering trying to add one. But, until now, besides the lack of an icon on the Integrations page, I wasn't aware this caused any problems.

**Comment by ildar170975** [comment]
Good news, the integration will be more perfect then )))

**Comment by pnbruckner** [comment]
Icon was approved.
