### ISSUE TITLE
Removed from HACS and now error in log upon HA reboot

### ISSUE THREAD

**Issue by walk0080** [pnbruckner/ha-composite-tracker#46]
2023-07-02 12:02:25.573 ERROR (MainThread) [homeassistant.setup] Setup failed for composite: Integration not found.

Home Assistant 2023.6.3

composite entries in configuration.yaml were removed.

**Comment by pnbruckner** [comment]
If you are no longer using the composite integration, then you need to remove the corresponding lines from your configuration YAML file(s.)

**Comment by pnbruckner** [comment]
Oh, ok, I couldn't tell that the last line in your original comment was not part of the error message. Then you probably also need to go to the Settings -> Devices & Services -> Integrations page and delete the Composite entry or entries.

**Comment by walk0080** [comment]
Yes also removed via HACS

strange

**Comment by walk0080** [comment]
That was it - some entries left in the integrations area. Thanks !
