### ISSUE TITLE
Deprecated constants which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by ExMacro** [pnbruckner/ha-composite-tracker#55]
Hi!

HA logs have the following mention that some of the constants used will be deprecated in a year. Thanks already beforehand if you have the time to fix this in the near future @pnbruckner !

```
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:205
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 17:48:27 (8 occurrences)
Last logged: 17:48:27

SOURCE_TYPE_BLUETOOTH was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.BLUETOOTH instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_BLUETOOTH_LE was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.BLUETOOTH_LE instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_GPS was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_ROUTER was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
```

**Comment by pnbruckner** [comment]
Those constants are still in the code for backward compatibility with older versions of HA. (I don't like to force my users to be on the latest & greatest HA release.) I happen to be in the process of making major changes to this integration, and those will all be removed as part of those changes.

Thanks for letting me know!

**Comment by ExMacro** [comment]
> Those constants are still in the code for backward compatibility with older versions of HA. (I don't like to force my users to be on the latest & greatest HA release.) I happen to be in the process of making major changes to this integration, and those will all be removed as part of those changes.
> 
> Thanks for letting me know!

Thanks @pnbruckner !
