### ISSUE TITLE
FR: add option to set entity_picture in UI

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-composite-tracker#56]
please consider as title, see community post on this request: https://community.home-assistant.io/t/composite-device-tracker-platform/67345/538

it would be very nice if we wouldn't need to customize an entity_picture (if we dont want any of the underlying trackers to provide the picture)

in my setup, I use dedicated images, to be able to 'see' these are not any of the individual trackers, but Composite integration entities.

Thanks for considering

**Comment by pnbruckner** [comment]
Can you provide some detail as to what you would like to use for the entity picture? E.g., what type(s) of value do you use for entity_picture under customize in YAML?

**Comment by Mariusthvdb** [comment]
currently I use:

```
homeassistant:

  customize:

    device_tracker.marijn_composite:
      entity_picture: /local/family/marijn_bmj.png
```

and the likes for my other family trackers.

because I also want the state-badge to indicate presence, like the icons change and get their state-colors if we wouldn't set an entity_picture:

<img width="76" alt="Scherm­afbeelding 2024-01-16 om 11 58 29" src="https://github.com/pnbruckner/ha-composite-tracker/assets/33354141/c2c7da66-8fd9-4208-be2c-414956a4d28e">

I use a card_mod on these entities:

```
      - entity: device_tracker.marijn_composite
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  filter:
                    {{'grayscale(100%)' if not is_state(config.entity,'home') else 'none'}};
                }
```

I guess, that brings me to a second part for this FR:

please also consider adding a filter on the state.  I wouldnt go as far as to follow all possible states on the tracker (it can also be a zone......) but main functionality of being 'home' or not being 'home' ( so I am explicitly not focussing on 'not_home' would be a very useful asset for the integration.

Also, because they would then get filtered when used in eg a Map card without requiring anything further.

A config option for the integration could be added to allow users to use this functionality or not

(its really odd currently, as I can not fake another state using the set state button in developer-tools. It loses the customization and returns to the regular icons. hmm

**Comment by pnbruckner** [comment]
> entity_picture: /local/family/marijn_bmj.png

So, a file path? To a file that already exists, and is accessible?

I could probably add that fairly easily, both YAML & UI. I'd have to test, however, if a local file would work in the entity's entity_picture attribute. I think it would, but I'd have to check to be sure.

I could also possibly add an option to upload a picture, kind of like what the person integration allows, which, of course, would be UI only.

Regarding the other part of the request, sorry, but I'm not following what you mean by a state filter, or how that might work for a device tracker integration.

**Comment by Mariusthvdb** [comment]
yes, a local file and accessible. 

> I could probably add that fairly easily, both YAML & UI. I'd have to test, however, if a local file would work in the entity's entity_picture attribute. I think it would, but I'd have to check to be sure.

suppose it could be like the person configuration had now too?

<img width="451" alt="Scherm­afbeelding 2024-01-16 om 15 46 52" src="https://github.com/pnbruckner/ha-composite-tracker/assets/33354141/14560749-17cb-45a2-a596-f3e509f8d91b">

Regarding the other part of the request, sorry, but I'm not following what you mean by a state filter, or how that might work for a device tracker integration.

All I meant was support for full color when 'home', and filter grayscale when not 'home'

we can add that with card_mod and the likes, but then it is per card, and not global.
If the integration could provide that based ion the state of the tracker, it would be much better

**Comment by pnbruckner** [comment]
> suppose it could be like the person configuration has too?

Yes, I said that: "I could also possibly add an option to upload a picture, kind of like what the person integration allows, which, of course, would be UI only."

Regarding the graying of the entity picture, that would be outside the scope of an integration like this. That is really a frontend thing, not a backend thing like an integration.

**Comment by Mariusthvdb** [comment]
sorry I didnt read carefully enough....

graying: thanks for the consideration and explanation

**Comment by pnbruckner** [comment]
I suppose it might be possible to add an option to specify a picture for home, and another picture for anything else, or even a number of pictures, one for each zone you care about (of which home might be one), and then a default picture for any state that doesn't match any of the specified zones.

But the user would have to supply the various pictures (possibly a color version and a grayscale version, etc.), it would probably only be "easy" to implement via YAML, I'm not sure how much use this would get, and therefore, whether it would be worth it, and lastly, even if it can be done in the backend integration, I'm not sure it makes sense to bundle in a feature like this. I just spent a lot of energy removing extra features, I don't think this one makes a lot of sense for the composite.

But thanks for the suggestion, anyway!

**Comment by Mariusthvdb** [comment]
if you allow me, a final consideration:

given the attention [state-color got when they were messed up in the Frontend](https://community.home-assistant.io/t/2022-12-color-states-are-broken-unusable/).... I suppose everyone using a device-tracker will want to _see_ the difference at least between home and no home in the icon/entity_picture.

yes we can do yaml mods, probably;y even use the officially supported [state-filter](https://www.home-assistant.io/dashboards/picture-entity/#state_filter) for some cards.

this is all very card centered, and not system wide (we can not set a filter in the theme state-color section, only, well, color....

so, providing a setting in the integration that would allow this to do inside the integration would help enormously.

yet I fully understand your take on frontend / backend.

o well, I am glad you are updating an simplifying ;-)

**Comment by pnbruckner** [comment]
The main problem is, AFAIK, a backend integration can only decide the value of the `entity_picture` attribute, it can't do anything about how it is rendered in the UI. So, to implement a feature like this, the user (you) would have to provide the different renderings, i.e., you'd have to supply multiple pictures per composite. Then I could implement something that selects which picture to use based on state.

**Comment by pnbruckner** [comment]
@Mariusthvdb have you tried 3.3.0b0 (with this feature) yet?

**Comment by Mariusthvdb** [comment]
o I had forgotten about that completely, my apologies!

<img width="419" alt="Scherm­afbeelding 2024-03-14 om 15 48 32" src="https://github.com/pnbruckner/ha-composite-tracker/assets/33354141/103c5aee-0c47-4bbe-826d-81e1ca6d22d4">

<img width="402" alt="Scherm­afbeelding 2024-03-14 om 16 43 18" src="https://github.com/pnbruckner/ha-composite-tracker/assets/33354141/3c662263-6f5d-4f29-b60e-1b80c776145d">

works fine!

only thing I miss is a preview, like we have in the Zones. its a bit strange to be selecting images without being able to see them.

**Comment by pnbruckner** [comment]
Yeah, I'm not going to add an image previewer. I would think most people don't have a zillion image files in that folder. In fact, most will probably just use the upload option anyway.
