### ISSUE TITLE
Entity_Id vs Entities

### ISSUE THREAD

**Issue by omayhemo** [pnbruckner/ha-composite-tracker#59]
The documentation speaks of a breaking change, migrating entity_id to entities.  The current version doesn't seem to support this so I'm confused.

**Comment by pnbruckner** [comment]
That is talking about an attribute of the `device_tracker` entities. It used to be `entiry_id`, but it didn't show up in the UI. It did appear on the STATES page, and it, of course, could be used in templates, etc. But I changed the name of the attribute to `entities`, so now you can see it in the "more info" box.

**Comment by omayhemo** [comment]
Ah, my mistake.
