### ISSUE TITLE
Make the integration's icon more visible in a dark theme

### ISSUE THREAD

**Issue by ildar170975** [pnbruckner/ha-composite-tracker#62]
Default dark theme:

![image](https://github.com/pnbruckner/ha-composite-tracker/assets/71872483/26727aef-1587-4d89-bdae-f75aee7bd82e)

Suggest to either invert the icon or use a colored one...
Or the same icon - but with a white background.

**Comment by pnbruckner** [comment]
Good idea. Obviously, I'm not an artist! But at least I can use Paint to fill in the background. 😄

**Comment by pnbruckner** [comment]
Yep, that's what I just did. Check out the link above to the PR in the home-assistant/brands repo.

**Comment by pnbruckner** [comment]
PR was accepted, so new icons should be available
