### ISSUE TITLE
advanced setup?

### ISSUE THREAD

**Issue by deanfourie1** [pnbruckner/ha-composite-tracker#71]
I am trying to setup a advanced location based sensor working with the device BSSID.

What I want to achieve,

Display an area name based on BSSID
eg. 12:34:33:11:cc:ab = Living Room / 23:ab:55:fc:22:12 = Kitchen etc.
When the device is not connected to a BSSID, display the state as “Away”
This to specifically be a “Device Tracker” allowing me to assign it to a User.
When the user is “Away”, switch to the GPS location of the device.
Where im at

Using the composite device_tracker integration, I have managed to convert sensors to device trackers allowing me to assign them to the Users as device trackers. This currently shows as “Unknown” as im assigning the BSSID sensor directly to the compose device_tracker as the entity and I guess it cannot determine the home or away state.
Where I am stuck:

I need to somehow create a template sensor or something that determines the BSSID and assigns the name to that sensor, then assign that sensor the compose device_tracker sensor.
Can someone help me with this as I can only seem to create template sensors to convert to a “Unit of Measurement”.

Also, is it possible to display the entities based on a weight, IE, when connected to Wifi, dislplay the BSSID entity, when wifi is disconnected, then use the GPS device tracker?

Thanks

**Comment by pnbruckner** [comment]
I think I understand what you're trying to achieve. Unfortunately, I don't think it's a good fit for the composite integration. I.e., I don't think it would work well to accept a (template) sensor and try to use that as an input to a composite tracker. The main reason is that the composite is based on state _changes_, not states.

Considering how you might do this, I suppose you could use the `device_tracker.see` service to combine your BSSID sensor and a composite device tracker entity. But that still uses the "legacy" device tracker infrastructure, and you might not want to mess with that.

Another alternative could possibly be using a [Python Script](https://www.home-assistant.io/integrations/python_script/) with an automation. The script could create an entry in the State Machine that combines the inputs and "looks like" a device tracker entity.

**Comment by pnbruckner** [comment]
I'm closing this since I don't think this fits the composite tracker integration, and since I haven't heard back from you. Feel free to reopen if you like.
