### ISSUE TITLE
HA v2024.5 - WARNING - cached_property was used from composite

### ISSUE THREAD

**Issue by jazzyisj** [pnbruckner/ha-composite-tracker#74]
This warning is showing up in HA v2024.5. 

`WARNING (ImportExecutor_0) [homeassistant.backports.functools] cached_property was used from composite, this is a deprecated alias which will be removed in HA Core 2025.5. Use functools.cached_property instead, please report it to the author of the 'composite' custom integration`

**Comment by pnbruckner** [comment]
Already fixed: 

https://github.com/pnbruckner/ha-composite-tracker/releases/tag/3.4.1

**Comment by jazzyisj** [comment]
Weird.  Didn't get an update notification and HACS wasn't showing the new version until I clicked Redownload.  Oh well.

Thanks!
