### ISSUE TITLE
Adding entities to setup crashes integration

### ISSUE THREAD

**Issue by Bosty01** [pnbruckner/ha-composite-tracker#78]
When I add my entities to the tracker, it gives me this error:

![Screenshot_21-7-2024_162855_homeassistant local](https://github.com/user-attachments/assets/92ecefb1-772f-4156-a38f-8d5bbceff403)
![Screenshot_21-7-2024_162935_homeassistant local](https://github.com/user-attachments/assets/90dcd357-5f44-4266-a764-d7080e1470ac)

**Comment by pnbruckner** [comment]
@Bosty01, sorry it's taken so long to respond.

Per the documentation:

> Currently any entity that has "GPS" attributes (`gps_accuracy` or `acc`, and either `latitude` & `longitude` or `lat` & `lon`), or any `device_tracker` entity with a `source_type` attribute of `bluetooth`, `bluetooth_le`, `gps` or `router`, or any `binary_sensor` entity, can be used as an input entity.

I'm guessing you manually typed in `sensor.brett_iphone_2_battery_level` and `sensor.brett_iphone_2_battery_state`, but those are not supported.

I'm wondering, why did you want to include those as inputs?
