### ISSUE TITLE
Composite fails to load with new Homeassistant 2024.08.0

### ISSUE THREAD

**Issue by Kilowatt-W** [pnbruckner/ha-composite-tracker#79]
Hello,

it looks like there is a problem in loading the composite tracker with the new Home Assistant version.

Errors from log:

2024-08-10 19:04:31.503 ERROR (MainThread) [homeassistant.config] Unknown error calling composite CONFIG_SCHEMA - async_get_hass called from the wrong thread
File "/config/custom_components/composite/__init__.py", line 89, in _entity_picture
2024-08-10 19:04:31.515 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'composite': Invalid config.

Before Update it was running without problems.

**Comment by mazdarx2001** [comment]
I have the new2024.8.0 and just installed this for the first time and tested it. It seems to be working fine. Just putting this out there in case the issue might only arise for those that installed before the update?

**Comment by Kilowatt-W** [comment]
It looks like there is a problem with the custom entity_picture. Removed it from config and its working again.

Greetings  Kilowatt

**Comment by pnbruckner** [comment]
Thanks! HA is a continually moving target. Argh!! I think I know what I need to do to fix this. In the meantime, either remove entity_picture from your YAML configuration, or switch to UI based configuration.

**Comment by pnbruckner** [comment]
@Kilowatt-W, if you could give 3.4.3b0 a try, I would appreciate it. You'll need to add `entity_picture` back to your YAML configuration. Let me know if it fixes the problem. Thanks!

**Comment by Kilowatt-W** [comment]
Tried in the morning works like a charm :-)

Thx for the fast repair,

greetings from austria
Kilowatt
