### ISSUE TITLE
Composite for (room)presence

### ISSUE THREAD

**Issue by CoMPaTech** [pnbruckner/ha-composite-tracker#81]
Hi @pnbruckner 

First up: Thanks for your great contributions to HA! Feel free to close if not applicable (as a contributor myself I'm aware users might have different use cases than the author).

I was looking for a proper way to composite my multiple device trackers, as a long time user of https://espresense.com I'm tracking my phone both using the HA Companion tracking but also indoors, though, since ESPresense can also recognise IRK it's possible to monitor a Watch also. So while `not_home` it will track using the companion, but `home` I would prefer following the bluetooth trackers. I'm in doubt if it falls in the use-case for ha-composite-tracker, but I thought I'd ask before checking further and/or dig in your code and PR.

Example device:
`state` will be set to a room(name)
`attributes` example:
```
source_type: espresense
friendly_name: My Phone
latitude: 12.3454212837415715 # yes espresense is very precise
longitude: 12.3454212837415715 # gps location is sample, precision is on par
gps_accuracy: 0
elevation: 4.9999999568589444
x: 2.5630434985379624 # espresense floorplan coordinates
y: 3.471941802488283
z: 4.9999999568589444
confidence: 90
fixes: 3
best_scenario: Attic # it has rooms per floor, so best_scenario is set to floorname, state to roomname
```

**Comment by pnbruckner** [comment]
I suppose anything is possible, but this doesn't actually fit the design and current implementation of the composite, which is (for the most part), "latest is greatest", meaning, it (normally) uses the location of the input entity with the most up-to-date data. Also, it (normally) doesn't try to force the state of the composite entity, leaving that to the device tracker component code to decide.

**Comment by CoMPaTech** [comment]
Latest is greatest would definitely work, I'll have to look how to get the zones over `home` I guess. Understood if it doesn't completely fits. Tnx!

**Comment by pnbruckner** [comment]
In the `_entity_updated` method, if you set `location_name` to a string, it will become the composite tracker entity's state (unless it's overwritten by `driving`, which in your scenario, is highly unlikely.)

**Comment by CoMPaTech** [comment]
Tnx @pnbruckner!
